config/routes.rb
Rails.application.routes.draw do
  
  get 'cam_search/index'

  get 'it_skills/ItItem'

  get 'ranking/have', to: 'ranking#have' 
  get 'ranking/want', to: 'ranking#want' 

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :it_skills
end

app/models/user.rb
class User < ActiveRecord::Base
before_save { self.email = self.email.downcase }

  validates :name, presence: true, length: { maximum: 100 }#　ユーザー名
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  #お問い合わせ用Eメール
  validates :RecruitEmail,length: { maximum: 200 } ,uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  
  #管理用Eメール
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  
  #電話番号
  validates :TelNam, length: { maximum: 15 }
  #fax
   validates :fax, length: { maximum: 15 }
  
  #Establishment ,"設立年月日"
  validates :Establishment, length: { maximum: 10 }
  
  #listing ,"上場有無"
  validates :listing, presence: true, length: { maximum: 2}
  
  #資本金　
  validates :Capitalstock, presence: true, length: { maximum: 15 }
  
  #:zipcode ,"郵便番号"
  validates :zipcode, presence: true, length: { maximum: 15 }
  #:dwelling ,"住所"
  validates :dwelling, length: { maximum: 2000 }
  
  #:BuildName ,"建物名"
  validates :BuildName, length: { maximum: 2000 }
  
  #企業公式HP
  validates :officialhp, length: { maximum: 2000 }
  
  ##企業自己紹介
  validates :Profile, length: { maximum: 2000 }
  
  
  #mount_uploader ：avatar,AvatarUploader 
  
  #ここまでがバリデション値
  has_many :microposts
  has_many :itskils
  
   has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
   # 中略
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
   def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
 def edit
  @user = User.find(params[:id])
end

 def update
  @user = User.find(params[:id])
   if  @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to edit_user_path(current_user)
      flash[:success] = "プロフィールを更新しました"
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ログインされました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  before_action :correct_user, only: [:edit, :update]
  
  def followings
      @user = User.find(params[:id])
      @followings = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users
  end
  
    private
    
    def user_params
      params.require(:user).permit(:name,:RecruitEmail, :email,:fax, :password,:password_confirmation,:TelNam,
      :Establishment,:listing,:zipcode,:dwelling,:BuildName,:Capitalstock,:officialhp,:area)
    end
    
    def correct_user
     @user = User.find(params[:id])
        redirect_to(root_path) unless @user == current_user 
   end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフの更新</h1>

  <p class="text-center">プロフィールにご変更があれば、更新してください</p>
  <div class="row">
     <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
    <div class="col-sm-5 well">
      
      <%= f.label :name,"ユーザー名" %></th>
      <%= f.text_field :name, class: 'form-control' %>
      <div class="well">
        
       
        <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
        <br>
         <br>
          <br>
      </div>
      <div class="well">
         <p>連絡先/パスワードの設定</p>
         <table class="table">
        	<tbody>
        		<tr>
        			<th><span class="glyphicon glyphicon-envelope" aria-hidden="true">　お問い合わせ</th>
        			<td><%= f.email_field :RecruitEmail, class: 'form-control' %></td>
        		</tr>
        			<th><span class="glyphicon glyphicon-envelope" aria-hidden="true">　サイト管理用</th>
        			<td><%= f.email_field :email, class: 'form-control' %></td>
        		</tr>
        		<tr>
        			<th><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></th>
        			<td><%= f.text_field :TelNam, class: 'form-control' %></td>
        		<tr>
        			<th><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></th>
        			<td><%= f.text_field :fax, class: 'form-control' %></td>
        		<tr>
        	</tbody>
        </table>
      
      </div>
       <div class="well">
        <p>SNS</p>
        <p>
          <span class="label label-default">News</span>
          <span class="label label-primary">W3Schools</span>
          <span class="label label-success">Labels</span>
          <span class="label label-info">Football</span>
          <span class="label label-warning">Gaming</span>
          <span class="label label-danger">Friends</span>
        </p>
      </div>
    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
         
      <div class="well">
        <p>企業情報</p>
        <table class="table">
	<tbody>
		<tr>
			<th><%= f.label :Establishment,"設立年月日" %></th>
			<th><%= f.label :listing ,"上場有無" %></th>
		<th><%= f.label :Capitalstock ,"資本金" %></th>
		</tr>
		<tr>
				<td> <%= f.text_field :Establishment, class: 'form-control' %></td>
			<td><%= f.text_field :listing, class: 'form-control' %></td>
			<td><%= f.text_field :Capitalstock, class: 'form-control' %></td>
		</tr>
		<tr>
			<th><%= f.label :officialhp ,"企業HP" %></th>
			<td colspan="2"><%= f.text_field :officialhp, class: 'form-control' %></td>
		</tr>
	</tbody>
</table>
      </div>
      
      <div class="well">
          <%= f.label :profile ,"企業自己紹介" %>
          <%= text_area :profile, :size => "100x20" %>
          </div>
      
        <div class="panel panel-default">
          <div class="panel-heading"><p>企業所在地</p></div>
               <div class="panel-body">
            <div class="table-responsive">
              <table class="table">
                <tbody>
                		
                		<tr>
                			<th><%= f.label :zipcode ,"郵便番号" %></th>
                			<td><%= f.text_field :zipcode %></td>
                    	</tr>
                		<tr>
                			<th> <%= f.label :dwelling ,"住所" %></th>
                			<td><%= f.text_field :dwelling %></td>
                		</tr>
                		<tr>
                			<th><%= f.label :BuildName ,"建物名" %></th>
                			<td> <%= f.text_field :BuildName, class: 'form-control' %></td>
                		</tr>
                		<tr>
                			<th></th>
                			<td></td>
                		</tr>
                	</tbody>
              </table>
             <%= f.submit "決定", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        
      </div>
      </div>
      </div>
  </div>

      
  
 <% end %>

app/views/users/followers.html.erb
<h1 class="followingfolower">followers list</h1>
<h2>user/followers.html.erb</h2>

<div class="col-xs-6 col-sm-push-3">
　<div class="panel panel-default">
  　<div class="panel-heading">現在、あなたをフォローされてる人です</div>
  　　<table class="table table-hover">
       <tbody>
    	　　<tr>
    	　　　<th>写真</th>
    	　　　<th>名前</th>
    	　　</tr>
    	　　　<tr>
    	　　　<% @followers.each do |user| %>
        		<td><%= gravatar_for(user) %></td>
        		<td><%= user.name %></td>
        	</tr>
 　　　　　　<% end %>
    	</tbody>
  　</table>
　</div>
</div>

app/views/users/followings.html.erb
<h1 class="followfollower">followings user lists</h1>
<h2>user/followings.html.erb</h2>

<div class="col-xs-6 col-sm-push-3">
　<div class="panel panel-default">
  　<div class="panel-heading">現在、あなたがフォローしてる人です</div>
  　　<table class="table table-hover">
       <tbody>
    	　　<tr>
    	　　　<th>写真</th>
    	　　　<th>名前</th>
    	　　</tr>
    	　　　<tr>
    	　　　<% @followings.each do |user| %>
    		<td><%= gravatar_for(user) %></td>
    		<td><%= user.name %></td>
    		</tr>
 　　　　　　<% end %>
    	</tbody>
  　</table>
　</div>
</div>

app/views/users/new.html.erb
<p class="text-center">プロフィールにご変更があれば、更新してください</p>
  <div class="row">
     <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
    <div class="col-sm-5 well">
      
      <%= f.label :name,"ユーザー名" %></th>
      <%= f.text_field :name, class: 'form-control' %>
      <div class="well">
        
       
        <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
        <br>
         <br>
          <br>
      </div>
      <div class="well">
         <p>連絡先/パスワードの設定</p>
         <table class="table">
        	<tbody>
        		<tr>
        			<th><span class="glyphicon glyphicon-envelope" aria-hidden="true">　お問い合わせ</th>
        			<td><%= f.email_field :RecruitEmail, class: 'form-control' %></td>
        		</tr>
        			<th><span class="glyphicon glyphicon-envelope" aria-hidden="true">　サイト管理用</th>
        			<td><%= f.email_field :email, class: 'form-control' %></td>
        		</tr>
        		<tr>
        			<th><span class="glyphicon glyphicon-envelope" aria-hidden="true"></th>
        			<td><%= f.text_field :fax, class: 'form-control' %></td>
        		</tr>
        		<tr>
        			<th><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></th>
        			<td><%= f.text_field :TelNam, class: 'form-control' %></td>
        		<tr>
        			<th><%= f.label :password,"管理用パスワード" %></th>
        			<td><%= f.password_field :password, class: 'form-control' %></td>
        		</tr>
        		<tr>
        			<th><%= f.label :password_confirmation, "管理用パスワードの確認" %></th>
        			<td><%= f.password_field :password_confirmation, class: 'form-control' %></td>
        		</tr>
        	</tbody>
        </table>
      
      </div>
       <div class="well">
        <p>SNS</p>
        <p>
          <span class="label label-default">News</span>
          <span class="label label-primary">W3Schools</span>
          <span class="label label-success">Labels</span>
          <span class="label label-info">Football</span>
          <span class="label label-warning">Gaming</span>
          <span class="label label-danger">Friends</span>
        </p>
      </div>
    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
         
      <div class="well">
        <p>企業情報</p>
        <table class="table">
        	<tbody>
        		<tr>
        			<th><%= f.label :Establishment,"設立年月日" %></th>
        			<th><%= f.label :listing ,"上場有無" %></th>
        			<th><%= f.label :Capitalstock ,"資本金" %></th>
        		</tr>
        		<tr>
        			<td><%= f.text_field :Establishment, class: 'form-control' %></td>
        			<td><%= f.text_field :listing, class: 'form-control' %></td>
        			<td><%= f.text_field :Capitalstock, class: 'form-control' %></td>
        		</tr>
        		<tr>
        			<th><%= f.label :officialhp ,"企業HP" %></th>
        			<td colspan="2"><%= f.text_field :officialhp, class: 'form-control' %></td>
        		</tr>
        	</tbody>
        </table>
      </div>
      
      <div class="well">
        <<%= f.label :Profile ,"企業自己紹介" %>
          <%= text_area :Profile, :size => "20x10" %>
          
          </div>
      
        <div class="panel panel-default">
          <div class="panel-heading"><p>企業所在地</p></div>
               <div class="panel-body">
            <div class="table-responsive">
              <table class="table">
          	<tbody>
          		<tr>
          			<th><%= f.label :zipcode ,"郵便番号" %></th>
          			<th><%= f.label :area ,"当道府県" %></th>
          		</tr>
          		<tr>
          			<td><%= f.text_field :zipcode, class: 'form-control' %></td>
          			<td><%= f.text_field :area , class: 'form-control'%></td>
          		<tr>
                			<th colspan="2"><%= f.label :dwelling ,"住　所：" %><%= f.text_field :dwelling, class: 'form-control' %></th>
                		</tr>
                		<tr>
                			<th colspan="2"><%= f.label :BuildName ,"建物名：" %><%= f.text_field :BuildName, class: 'form-control' %></th>
                		</tr>
                		<tr>
                			<th></th>
                			<td></td>
                		</tr>
                	</tbody>
          </table>
          
             <%= f.submit "決定", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        
      </div>
      </div>
      </div>
  </div>

 <% end %>

app/views/users/show.html.erb
<h1><small>ユーザー情報</small></h1>
      <hr>
<div class="row content">
    <div class="col-sm-4 ">
      <div class="well">
         <h3><%= @user.name %></h3> 
     <section class="user_info">
      <p>
        <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
        <%= gravatar_for @user %></p>
      
    </section>
    <br>
    <ul class="list-group">
        <li class="list-group-item"><%= link_to "ツイート", root_path(@user) %><span class="badge"><%= @user.microposts.count %></span></li>
        <li class="list-group-item"><%= link_to "フォロー", followings_user_path(@user) %><span class="badge"><%= @user.following_users.count %></span></li>
        <li class="list-group-item"><%= link_to "フォロワー", followers_user_path(@user) %><span class="badge">0</span></li>
      </ul>
 </div>
</div>

  <div class="col-sm-4">
<div class="panel panel-primary">
      <div class="panel-heading">ユーザー連絡先</div>
      <div class="panel-body">
    
      <span class="glyphicon glyphicon-envelope" aria-hidden="true">お問い合わせ：</span>
      <%= @user.RecruitEmail %><br>
      <span class="glyphicon glyphicon-phone-alt" aria-hidden="true">T　　E　　L：</span>
      <%= @user.TelNam %><br>
      <span class="glyphicon glyphicon-phone-alt" aria-hidden="true">F　　A　　X：</span>
      <%= @user.fax %><br>
       <span class="glyphicon glyphicon-home" aria-hidden="true">公式サイト ：</span>
      <%= @user.officialhp %><br>
     
</div>
  </div>
  
  <div class="panel panel-default">
  <div class="panel-heading">企業情報</div>
  <div class="panel-body">
    <table class="table table-bordered">
	<tbody>
		<tr>
			<th><%= f.label :Establishment ,"設立年月日" %></th>
			<td><%= @user.Establishment %></td>
		</tr>
		<tr>
			<th><%= f.label :listing ,"上場有無" %></th>
			<td><%= @user.listing %></td>
		</tr>
		<tr>
			<th><%= f.label :Capitalstock ,"資本金" %></th>
			<td><%= @user.Capitalstock %>万円</td>
		</tr>
		<tr>
			<th><%= f.label :zipcode ,"郵便番号" %></th>
			<td><%= @user.zipcode %></td>
		</tr>
		<tr>
			<th><%= f.label :dwelling ,"住所" %></th>
			<td><%= @user.area %><%= @user.dwelling %></td>
		</tr>
		<tr>
			<th><%= f.label :BuildName ,"建物名" %></th>
			<td><%= @user.BuildName %></td>
		</tr>
	</tbody>
</table>
  </div>
</div>
</div>
<div class="col-sm-4">
  <div class="panel panel-default">
  <div class="panel-heading">この企業様のIT技術者不足情報</div>
  <div class="panel-body">
    グラフ解析結果
    <p>グラフ長さが大きいほど不足してます。</p>
    </div>
</div>
</div>
<div class="col-sm-12">
<div class="panel panel-info">
      <div class="panel-heading">企業PR</div>
      <div class="panel-body">
        <%= @user.Profile %>
      </div>
    </div>
    <% end %>
 </div> 
    <div class="col-sm-12">
      <h1><small>ユーザー技術データ</small></h1>
      <hr>
      
      <div class="panel panel-default">
	<div class="panel-heading">
		<h5 class="panel-title">主なIT活動</h5>
	</div>
	<div class="panel-body">
		<section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>受託/常駐割合</h4>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>開発ジャンル</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>業務領域</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>担当業界</h4>
              <span class="text-muted">Something else</span>
            </div>
      </section>
	</div>
</div>
  <div class="panel panel-success">
	<div class="panel-heading">
		<small>お取り扱い中のIT技術</small>
	</div>
	<div class="panel-body">
		<section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>プログラミング言語</h6>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>フレームワーク</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>バージョン管理システム</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>CSM開発</h6>
              <span class="text-muted">Something else</span>
            </div>
      </section>
      	<section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>OS</h6>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>ミドルウエア</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>アプリケーション</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>CSM開発</h6>
              <span class="text-muted">Something else</span>
            </div>
      </section>
      <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>ソフトウエア</h6>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>デザイン</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>その他</h6>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h6>未登録</h6>
              <span class="text-muted">Something else</span>
            </div>
      </section>
	</div>
</div>

    </div>
    
  </div>