config/routes.rb
Rails.application.routes.draw do
  
  get 'cam_search/index'

  get 'it_skills/ItItem'

  get 'ranking/have', to: 'ranking#have' 
  get 'ranking/want', to: 'ranking#want' 

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :it_skills
end

app/models/it_skill.rb
class ItSkill < ActiveRecord::Base
  belongs_to :user
  #alidates :user_id, presence: true
   #mount_uploader :Skilllogo, SkilllogoUploader
end

app/controllers/it_skills_controller.rb
class ItSkillsController < ApplicationController
  before_action :set_it_skill, only: [:show, :edit, :update, :destroy]
   before_action :logged_in_user, only: [:create]

  # GET /it_skills
  # GET /it_skills.json
  def index
    @it_skills = ItSkill.all
  end

  # GET /it_skills/1
  # GET /it_skills/1.json
  def show
  end

  # GET /it_skills/new
  def new
    @it_skill = ItSkill.new
  end

  # GET /it_skills/1/edit
  def edit
  end
  
  def ItItem
  end

  # POST /it_skills
  # POST /it_skills.json
  def create
    @it_skill = ItSkill.new(it_skill_params)

    respond_to do |format|
      if @it_skill.save
        format.html { redirect_to @it_skill, notice: 'It skill was successfully created.' }
        format.json { render :show, status: :created, location: @it_skill }
      else
        format.html { render :new }
        format.json { render json: @it_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /it_skills/1
  # PATCH/PUT /it_skills/1.json
  def update
    respond_to do |format|
      if @it_skill.update(it_skill_params)
        format.html { redirect_to @it_skill, notice: 'ITアイテム更新しました.' }
        format.json { render :show, status: :ok, location: @it_skill }
      else
        format.html { render :edit }
        format.json { render json: @it_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /it_skills/1
  # DELETE /it_skills/1.json
  def destroy
    @it_skill.destroy
    respond_to do |format|
      format.html { redirect_to it_skills_url, notice: 'It skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_it_skill
      @it_skill = ItSkill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def it_skill_params
      params.require(:it_skill).permit(:ITimage, :ITName, :user_id, :existence, :educate, :Field, :Itgenre, :Accession, 
      :Resident, :TypeIndustry, :dgpn, :dbweb, :dbopen, :dbnclusion, :dbfirmware, :dbcontrol, :frequency, :ITRemarks,
      :Skilllogo)
    end
end

app/views/it_skills/ItItem.html.erb
<div class="container">
  	<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">検索ワード</h3>
  </div>
  <div class="panel-body">
      
    <table class="table">
	<tbody>
		<tr>
			<th>IT技術名</th>
			<td><input type="text" id="name" /></td>
		</tr>
		<tr>
			<th>ITジャンル</th>
			<td><input type="text" id="name" /></td>
		</tr>
		<tr>
			<th>属性</th>
			<td><input type="text" id="name" /></td>
		</tr>
	</tbody>
</table>
<p class="button"><input type="submit" value="検索結果へGO!" class="btn btn-primary"></p>
  </div>
</div>
</div>
  <div class="col-sm-8">
  	<div class="well">
      <p>ボタン一覧</p>
      <table class="table">
	<tbody>
		<tr class="info">
			<th>番号</th>
			<th>ボタン名</th>
			<td>該当技術に対する内容</td>
		</tr>
		<tr>
			<th>１</th>
			<th>HAVE</th>
			<td>自分が所持しており、実務使用可能であること</td>
		</tr>
		<tr>
			<th>２</th>
			<th>instruct</th>
			<td>自主学習だけでなく、教育できる設備やその支援制度有</td>
		</tr>
		</tr>
		<tr>
			<th>３</th>
			<th>inspection</th>
			<td>この技術を面接などで適性検査を実施することがある。</td>
		<tr>
		</tr>
	</tbody>
</table>
    </div>
  </div>
</div>

    <div class="col-sm-12">
   　<hr>
      <h4><small>ITアイテム</small></h4>
      <hr>
      <h2>ボタンの押し方を確認の上で検索してください</h2>
      <div class="row">
    <div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      
      <div class="caption">
        <h3>Thumbnail label</h3>
       <p>Current Project</p>
       
       
        <div class="well">
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
      </div>
    </div>
    </div>
    <div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>Current Project</p>
        <div class="well">
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
      </div>
    </div>
    </div>
    <div class="col-sm-6 col-md-4">
    	<div class="thumbnail">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>Current Project</p>
        <div class="well">
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
      </div>
    </div>
    </div>
      
    </div>
    </div>
  </div>
</div>　
　

app/views/it_skills/_form.html.erb
<%= form_for(@it_skill) do |f| %>
  <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
      <div class="well">
            <div class="well">
        <%= f.label :ITName,'IT技術名' %><%= f.text_field :ITName %>
        <div class="well">
         <%= f.file_field :ITimage %> 
        　
        　
         </div>
      </div>
      <div class="well">
        <table class="table table-striped">
    <tbody>
      <tr>
        <td><%= f.label :Itgenre,'ITジャンル' %></td>
        <td><%= f.text_field :Itgenre %></td>
      </tr>
      <tr>
        <td><%= f.label :existence,'該当案件' %></td>
        <td><%= f.text_field :existence %></td>
      </tr>
      <tr>
        <td><%= f.label :educate ,'教育体制' %></td>
        <td><%= f.text_field :educate %></td>
      </tr>
      <tr>
        <td><%= f.label :Field,'属性' %></td>
        <td> <%= f.text_field :Field %></td>
      </tr>
      <tr>
        <td><%= f.label :frequency ,'使用頻度率（％）' %></td>
        <td><%= f.text_field :frequency %></td>
      </tr>
    </tbody>
  </table>
      </div>
      <p><%= link_to '一覧表に戻る', it_skills_path %></p>
      </div>
    </div>
    <div class="col-sm-5 text-left">
      <div class="panel panel-default text-left">
        <div class="panel-heading">
              <p contenteditable="true">HAVE</p>
        </div>
          <div class="panel-body">
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
          </div>
      </div>
      <div class="panel panel-default text-left">
        <div class="panel-heading">
              <p contenteditable="true">WHONT</p>
        </div>
          <div class="panel-body">
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
          </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= f.label :TypeIndustry,'担当業種' %></div>
            <div class="panel-body  text-left">
              <%= f.text_field :TypeIndustry %>
              </div>
          </div>
      </div>
    </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= f.label :Remarks,'備考' %></div>
            <div class="panel-body  text-left">
              <%= text_area :ITemarks, :size => "300x500" %>
              </div>
          </div>
      </div>
    </div>
      
    </div>
    <div class="col-sm-3 sidenav">
      <div class="well">
        <p>受託開発割合</p>
        <table class="table">
      	<tbody>
      		<tr>
      			<th colspan="2"></th>
      		</tr>
      		<tr>
      			<th><%= f.label :Accession,'受託' %></th>
      			<td><%= f.number_field :Accession %></td>
      		</tr>
      		<tr>
      			<th><%= f.label :Resident,'常駐' %></th>
      			<td><%= f.number_field :Resident %></td>
      		</tr>
      	</tbody>
      </table>
      </div>
      <div class="panel panel-default">
            <div class="panel-heading">開発ジャンル</div>
            <div class="panel-body">
              <table class="table">
            	<tbody>
            	  <tbody>
            		<tr>
            			<th><%= f.label :dgpn,'汎用機系' %></th>
            			<td><%= f.number_field :dbnclusion %></td>
            		</tr>
            		</tr>
            		<tr>
            			<th> <%= f.label :dbweb,'WEB' %></th>
            			<td><%= f.number_field :dgpn %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbopen,'OPEN' %></th>
            			<td><%= f.number_field :dbweb %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbnclusion,'組み込み' %></th>
            		<td><%= f.number_field :dbopen %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbfirmware,'ファームウエア' %></th>
            			<td><%= f.number_field :dbfirmware %></td>
            		</tr>
            		<tr>
            			<th> <%= f.label :dbcontrol,'制御' %></th>
            			<td><%= f.number_field :dbcontrol %></td>
            		</tr>
            		<tr>
            	</tbody>
            </table>
            </div>
          </div>
      <div class="well">
        <%= f.submit '登録',class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/it_skills/edit.html.erb
<h1>変更登録</h1>

<%= render 'form' %>

app/views/it_skills/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <div class="panel panel-default">
  <div class="panel-heading"><h4>ITジャンル一覧</h4></div>
        <div class="panel-body">

       <li class="list-group-item"><%= link_to "プログラミング言語", '#'  %></li>
            　<li class="list-group-item"><%= link_to "フレームワーク", '#' %></li>
              　<li class="list-group-item"><%= link_to "データベース", '#' %></li>
              　<li class="list-group-item"><%= link_to "バージョン管理システム",'#' %></li>
              　<li class="list-group-item"><%= link_to "CMS開発", '#' %></li>
              　<li class="list-group-item"><%= link_to "OS", '#' %></li>
              　<li class="list-group-item"><%= link_to "ミドルウェア", '#' %></li>
              　<li class="list-group-item"><%= link_to "アプリケーション", '#' %></li>
              　<li class="list-group-item"><%= link_to "語学", '#' %></li>
              　<li class="list-group-item"><%= link_to "資格", '#' %></li>
              　<li class="list-group-item"><%= link_to "デザイン", '#' %></li>
              　<li class="list-group-item"><%= link_to "その他", '#' %></li>
              　
      </ul><br>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search Blog..">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    </div>
</div>
</div>

    <div class="col-sm-10">
      <div class="panel panel-default">
  <div class="panel-heading">登録技術一覧表</div>
  <div class="panel-body">
<p>内容の詳細と変更を行いたい場合はITスキル名のリンクよりご変更ください</p>
<p><%= link_to 'IT技術新規登録', new_it_skill_path %></p>
<table class="table">
  <thead>
    <tr class="success">
      <th>選択</th>
      <th>ロゴ</th>
      <th>Itスキル名</th>
      <th>属性</th>
      <th>Itジャンル</th>
      <th>受託</th>
      <th>常駐</th>
      <th>担当業種</th>
      <th>汎用機系</th>
      <th>WEB</th>
      <th>OPEN</th>
      <th>組み込み</th>
      <th>ファームウエア</th>
      <th>制御</th>
      <th>使用頻度率</th>
      <th>手続き</th>
    </tr>
  </thead>

  <tbody>
    <% @it_skills.each do |it_skill| %>
      <tr>
        <td><input type="checkbox" value="checkboxA"></td>
        <td>
          <%= it_skill.ITimage %></td>
        <td><%= link_to it_skill.ITName, it_skill %></td>
        <td><%= it_skill.Field %></td>
        <td><%= it_skill.Itgenre %></td>
        <td><%= it_skill.Accession %></td>
        <td><%= it_skill.Resident %></td>
        <td><%= it_skill.TypeIndustry %></td>
        <td><%= it_skill.dgpn %></td>
        <td><%= it_skill.dbweb %></td>
        <td><%= it_skill.dbopen %></td>
        <td><%= it_skill.dbnclusion %></td>
        <td><%= it_skill.dbfirmware %></td>
        <td><%= it_skill.dbcontrol %></td>
        <td><%= it_skill.frequency %></td>
        <td><%= link_to 'Destroy', it_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>



    </div>
  </div>
</div>

app/views/it_skills/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

app/views/it_skills/show.html.erb
<p id="notice"><%= notice %></p>
<h2>詳細をご確認の上でご変更リンクよりご登録ください</h2>
<%= form_for(@it_skill) do |f| %>
  <% if @it_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@it_skill.errors.count, "error") %> prohibited this it_skill from being saved:</h2>

      <ul>
      <% @it_skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
      <div class="well">
            <div class="well">
        　（<%= f.label :ITName,'IT技術名' %>）　<%= @it_skill.ITName %>
        <div class="well">
        <p><%= f.label :ITimage,'ITスキルロゴ' %>：<%= @it_skill.ITimage %></p>
         </div>
      </div>
      <div class="well">
　　　　　<table class="table table-striped">
    <tbody>
      <tr>
        <td><%= f.label :Itgenre,'ITジャンル' %></td>
        <td><%= @it_skill.Itgenre %></td>
      </tr>
      <tr>
        <td><%= f.label :existence,'該当案件' %></td>
        <td><%= @it_skill.existence %></td>
      </tr>
      <tr>
        <td><%= f.label :educate ,'教育体制' %></td>
        <td><%= @it_skill.educate %></td>
      </tr>
      <tr>
        <td><%= f.label :Field,'属性' %></td>
        <td><%= @it_skill.Field %></td>
      </tr>
      <tr>
        <td><%= f.label :frequency ,'使用頻度率（％）' %></td>
        <td><%= @it_skill.frequency %></td>
      </tr>
    </tbody>
  </table>
      </div>
      <p><%= link_to '一覧表に戻る', it_skills_path %></p>
      <p><%= link_to '変更', edit_it_skill_path(@it_skill) %></p>
      </div>
    </div>
    <div class="col-sm-6 text-left">
      <div class="panel panel-default text-left">
        <div class="panel-heading">
              <p contenteditable="true">HAVE</p>
        </div>
          <div class="panel-body">
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
          </div>
      </div>
      <div class="panel panel-default text-left">
        <div class="panel-heading">
              <p contenteditable="true">WHONT</p>
        </div>
          <div class="panel-body">
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>
          </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
            <%= f.label :TypeIndustry,'担当業種' %><br>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <%= @it_skill.TypeIndustry %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= f.label :Remarks,'備考' %></div>
            <div class="panel-body  text-left">
              <%= @it_skill.ITRemarks %>
              </div>
          </div>
      </div>
    </div>
      <div class="row">
        
      </div>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
        <p>受託開発割合</p>
        <table class="table">
      	<tbody>
      		<tr>
      			<th colspan="2"></th>
      		</tr>
      		<tr>
      			<th><%= f.label :Accession,'受託' %></th>
      			<td><%= @it_skill.Accession %></td>
      		</tr>
      		<tr>
      			<th><%= f.label :Resident,'常駐' %></th>
      			<td><%= @it_skill.Resident %></td>
      		</tr>
      	</tbody>
      </table>
      </div>
      <div class="panel panel-default">
            <div class="panel-heading">開発ジャンル</div>
            <div class="panel-body">
              <table class="table">
            	<tbody>
            	  <tbody>
            		<tr>
            			<th><%= f.label :dgpn,'汎用機系' %></th>
            			<td><%= @it_skill.dbnclusion %></td>
            		</tr>
            		</tr>
            		<tr>
            			<th> <%= f.label :dbweb,'WEB' %></th>
            			<td><%= @it_skill.dgpn %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbopen,'OPEN' %></th>
            			<td><%= @it_skill.dbweb %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbnclusion,'組み込み' %></th>
            		<td><%= @it_skill.dbopen %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbfirmware,'ファームウエア' %></th>
            			<td><%= @it_skill.dbfirmware %></td>
            		</tr>
            		<tr>
            			<th><%= f.label :dbcontrol,'制御' %></th>
            			<td><%= @it_skill.dbcontrol %></td>
            		</tr>
            		<tr>
            	</tbody>
            </table>
            </div>
          </div>
      
    </div>
  </div>
</div>
<% end %>