config/routes.rb
Rails.application.routes.draw do
  
  get 'cam_search/index'

  get 'it_skills/ItItem'

  get 'ranking/have', to: 'ranking#have' 
  get 'ranking/want', to: 'ranking#want' 

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :it_skills
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "カムスキ", root_path, id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ランキング", ranking_have_path %></li>
         <li><%= link_to "企業検索", cam_search_index_path %></li>
        <% if logged_in? %>
        
           <li><%= link_to "ITアイテム",it_skills_ItItem_path %></li>
           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              IT獲得関連 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "獲得ITアイテム設定", it_skills_path(current_user) %></li>
              <li><%= link_to "内容未定", '#' %></li>
              <li><%= link_to "内容未定", '#' %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "プロフ更新", edit_user_path(current_user) %></li>
              <li><%= link_to "パスワード変更", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>kamsuki</title>
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="pretty-checkbox.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
</head>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
</body>
</html>